# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CICD for self-host

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/banking-app-0.0.1-SNAPSHOT.jar banking-app-${{github.sha}}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: ofb-scoring
          path: banking-app-${{github.sha}}.jar


  fake-deploy:
    runs-on: self-hosted
    needs: run-unit-tests
    steps:
      - name: Get the artifact
        uses: actions/download-artifact@master
        with:
          name: banking-app
      - name: Fake deploy
        run: ls ofb-scoring*.jar
